# -- Project settings:
exp_name: PKG_sampledata_pseudo_labels
notes: none
project: 
entity: 


# -- External knowledge settings:
need_external_knowledge: True
external_knowledge_ready: False
segment_wikistep_sim_scores_ready: True
nodes_formed: False
edges_formed: False
topics_formed: False
#pseudo_label_VNM_ready: False
#pseudo_label_VTM_ready: False
#pseudo_label_TCL_ready: False
#pseudo_label_NRL_ready: False


# -- wikiHow settings:
wikihow_dir: pkg_data/wikiHow/partial
wikihow_num_tasks: 1053
#wikihow_dir: pkg_data/wikiHow/full
#wikihow_num_tasks: 215365


# -- HowTo100M settings: # TODO: adapt it to also CAE
howto100m_dir: pkg_data/howto100m
howto100m_num_tasks: 1059 # TO CHECK
#howto100m_num_tasks: 123520 # FULL
video_meta_csv_path: pkg_data/howto100m/HowTo100M_v1.csv
task_id_to_task_name_csv_path: pkg_data/howto100m/task_ids.csv


# -- Alignment settings:
use_captions: True
#sub_dir: pkg_data/cae/subtitles
sub_dir: pkg_data/howto100m/subtitles
#frame_dir: pkg_data/cae/videos
frame_dir: pkg_data/howto100m/videos


# -- Graph structure settings:
graph_structure: local
# graph_structure: global (paprika's original structure)

# -- For Local graph (based on task similarity) settings:
task_dir: pkg_data/cae/task_titles
#task_dir: pkg_data/howto100m/task_titles
task_clustering_linkage: average
task_clustering_distance_thresh: 0.5
task_clustering_affinity: cosine
#num_tasks: (depends on the video resources used)


# -- Graph node settings:
remove_step_duplicates: True
step_clustering_linkage: single
step_clustering_distance_thresh: 0.09
step_clustering_affinity: cosine
num_nodes: 10038
# 10038 if remove_step_duplicates or 10588 if not
# nodes is number of wikihow step_headlines


# -- Graph edge settings:
graph_find_matched_steps_criteria: topK
# {threshold | threshold+topK | topK}
graph_find_matched_steps_for_segments_thresh: 10
graph_find_matched_steps_for_segments_topK: 3
edge_min_aggconf: 1000


# -- Pseudo label settings:
# ---- VNM
label_find_matched_nodes_criteria: topK
# {threshold | threshold+topK | topK}
label_find_matched_nodes_for_segments_thresh: 8
label_find_matched_nodes_for_segments_topK: 3

# ---- VTN
label_find_tasks_criteria: topK
# {threshold | threshold+topK | topK}
label_find_tasks_thresh: 50
label_find_tasks_topK: 20

# ---- TCL
label_find_tasknodes_criteria: topK
# {threshold | threshold+topK | topK}
label_find_tasknodes_thresh: 50
label_find_tasknodes_topK: 20
label_num_howto100m_tasks_to_consider: 3

# ---- NRL
label_find_neighbors_criteria: topK
# {threshold | threshold+topK | topK}
label_find_neighbors_thresh: 0.5
label_find_neighbors_topK: 20
label_khop: 2


# -- General settings:
seed: -1
# seed is -1 means random, otherwise put a seed number that is greater than 0
curr_time: -1
num_workers: 8
# num_workers -1 will dynamically compute the number of available workers
working_abspath: 
partition_dataset: False


# -- Output settings:
checkpoint_dir: /mount/arbeitsdaten/jp-silberer/ernie_vil/model/paprika/output_checkpoints/
log_dir: output_logs
